<?php

$fiisArray = [
    'ABCP11',
    'AFHI11',
    'AFOF11',
    'AIEC11',
    'ALMI11',
    'ALZR11',
    'APTO11',
    'ARCT11',
    'ARRI11',
    'ATSA11',
    'BARI11',
    'BBFI11B',
    'BBFO11',
    'BBIM11',
    'BBPO11',
    'BBRC11',
    'BCFF11',
    'BCIA11',
    'BCRI11',
    'BICR11',
    'BLCA11',
    'BLCP11',
    'BLMC11',
    'BLMG11',
    'BLMR11',
    'BMLC11',
    'BNFS11',
    'BPFF11',
    'BPML11',
    'BRCO11',
    'BRCR11',
    'BREV11',
    'BRLA11',
    'BTAL11',
    'BTCR11',
    'BTLG11',
    'BTRA11',
    'BTWR11',
    'BZLI11',
    'CACR11',
    'CARE11',
    'CBOP11',
    'CCRF11',
    'CEOC11',
    'CJCT11',
    'CNES11',
    'CORM11',
    'CPFF11',
    'CPTS11',
    'CRFF11',
    'CTXT11',
    'CVBI11',
    'CXCE11B',
    'CXCO11',
    'CXRI11',
    'CXTL11',
    'CYCR11',
    'DEVA11',
    'DRIT11B',
    'DVFF11',
    'EDFO11B',
    'EDGA11',
    'EQIN11',
    'ERCR11',
    'EURO11',
    'EVBI11',
    'FAED11',
    'FAMB11B',
    'FATN11',
    'FCFL11',
    'FEXC11',
    'FIGS11',
    'FIIB11',
    'FIIP11B',
    'FISC11',
    'FIVN11',
    'FLCR11',
    'FLMA11',
    'FLRP11',
    'FMOF11',
    'FPAB11',
    'FVPQ11',
    'GALG11',
    'GAME11',
    'GCFF11',
    'GCRI11',
    'GESE11B',
    'GGRC11',
    'GSFI11',
    'GTLG11',
    'GTWR11',
    'HAAA11',
    'HABT11',
    'HBRH11',
    'HCHG11',
    'HCRI11',
    'HCTR11',
    'HFOF11',
    'HGBS11',
    'HGCR11',
    'HGFF11',
    'HGIC11',
    'HGLG11',
    'HGPO11',
    'HGRE11',
    'HGRS11',
    'HGRU11',
    'HLOG11',
    'HOSI11',
    'HPDP11',
    'HRDF11',
    'HREC11',
    'HSAF11',
    'HSLG11',
    'HSML11',
    'HSRE11',
    'HTMX11',
    'HUSC11',
    'IBCR11',
    'IBFF11',
    'IDFI11',
    'IFID11',
    'IFIE11',
    'IRDM11',
    'IRIM11',
    'JFLL11',
    'JPPA11',
    'JRDM11',
    'JSRE11',
    'KFOF11',
    'KINP11',
    'KISU11',
    'KNCR11',
    'KNHY11',
    'KNIP11',
    'KNRE11',
    'KNRI11',
    'KNRI11',
    'KNSC11',
    'LASC11',
    'LFTT11',
    'LGCP11',
    'LUGG11',
    'LVBI11',
    'MALL11',
    'MATV11',
    'MAXR11',
    'MBRF11',
    'MCCI11',
    'MCHF11',
    'MCHY11',
    'MFAI11',
    'MFII11',
    'MGCR11',
    'MGFF11',
    'MGHT11',
    'MGLG11',
    'MORC11',
    'MORE11',
    'MXRF11',
    'NAVT11',
    'NEWL11',
    'NEWU11',
    'NSLU11',
    'NVHO11',
    'NVIF11B',
    'ONEF11',
    'ORPD11',
    'OUFF11',
    'OUJP11',
    'OULG11',
    'OURE11',
    'PABY11',
    'PATC11',
    'PATL11',
    'PLCR11',
    'PLOG11',
    'PLRI11',
    'PORD11',
    'PQAG11',
    'PQDP11',
    'PRSV11',
    'PVBI11',
    'QAGR11',
    'QAMI11',
    'QIRI11',
    'RBCO11',
    'RBDS11',
    'RBED11',
    'RBFF11',
    'RBGS11',
    'RBHG11',
    'RBHY11',
    'RBIR11',
    'RBLG11',
    'RBRD11',
    'RBRF11',
    'RBRL11',
    'RBRP11',
    'RBRR11',
    'RBRS11',
    'RBRY11',
    'RBVA11',
    'RBVO11',
    'RCRB11',
    'RDPD11',
    'RECR11',
    'RECT11',
    'RECX11',
    'RELG11',
    'RFOF11',
    'RMAI11',
    'RNDP11',
    'RNGO11',
    'RRCI11',
    'RVBI11',
    'RZAG11',
    'RZAK11',
    'RZTR11',
    'SADI11',
    'SARE11',
    'SCPF11',
    'SDIL11',
    'SEQR11',
    'SHPH11',
    'SNCI11',
    'SNFF11',
    'SPTW11',
    'SPVJ11',
    'STRX11',
    'TEPP11',
    'TGAR11',
    'TORD11',
    'TRNT11',
    'TRXF11',
    'URPR11',
    'VCJR11',
    'VCRR11',
    'VGHF11',
    'VGIP11',
    'VGIR11',
    'VIFI11',
    'VILG11',
    'VINO11',
    'VISC11',
    'VIUR11',
    'VJFD11',
    'VLOL11',
    'VOTS11',
    'VRTA11',
    'VSHO11',
    'VSLH11',
    'VTLT11',
    'VVPR11',
    'VXXV11',
    'WPLZ11',
    'WTSP11B',
    'XPCA11',
    'XPCI11',
    'XPCM11',
    'XPHT11',
    'XPIN11',
    'XPLG11',
    'XPML11',
    'XPPR11',
    'XPSF11',
    'XTED11',
    'YUFI11B'
];

function calculate_median($arr)
{
    $count = count($arr); //total numbers in array
    $middleval = floor(($count - 1) / 2); // find the middle value, or the lowest middle value
    if ($count % 2) { // odd number, middle is the median
        $median = $arr[$middleval];
    } else { // even number, calculate avg of 2 medians
        $low = $arr[$middleval];
        $high = $arr[$middleval + 1];
        $median = (($low + $high) / 2);
    }
    return $median;
}

function calculate_average($arr)
{
    $count = count($arr); //total numbers in array]
    $total = 0;
    foreach ($arr as $value) {
        $total = $total + $value; // total value of array numbers
    }
    $average = ($total / $count); // get average value
    return $average;
}

$return = "";
foreach ($fiisArray as $fii) {
    $fii = explode('1', $fii)[0];
    echo "Parsing $fii" . PHP_EOL;
    $queryString = "{\"identifierFund\":\"$fii\"}";
    $queryUrl = "https://sistemaswebb3-listados.b3.com.br/fundsProxy/fundsCall/GetListedSupplementFunds/" . base64_encode($queryString);

    $response = json_decode(file_get_contents($queryUrl), true);
    $dividends = $response['cashDividends'];
    if($dividends){
        $paymentsMonthly = array();
        foreach ($dividends as $payment) {
            $date = $payment['paymentDate'];
            $dateSplitSlashes = explode('/', $date);
            $month = intval($dateSplitSlashes[1]);
            $rate = floatval(str_replace(',', '.', $payment['rate']));
            $paymentsMonthly[$month] += $rate;
        }
        $median = calculate_median(array_values($paymentsMonthly));
        $mean = calculate_average(array_values($paymentsMonthly));
        $return = $return . $fii . '    ' . abs($mean - $median) . PHP_EOL;
    }
    else{
        $return = $return . $fii . '    ' . 'NOT FOUND' . PHP_EOL;
    }
}

file_put_contents(__DIR__ . '/fii_dym.txt', $return);